export const diverseTypes = [
    { label: "Dining Table", value: "dining_table", description: "A table designed for eating meals, typically found in a dining room." },
    { label: "Coffee Table", value: "coffee_table", description: "A low table placed in a living room, often in front of a sofa, used for drinks, magazines, and decoration." },
    { label: "Bedside Table", value: "bedside_table", description: "A small table placed beside a bed, used for items like lamps, books, and alarm clocks." },
    { label: "Console Table", value: "console_table", description: "A narrow table often placed against a wall, used for decoration and storage." },
    { label: "Office Desk", value: "office_desk", description: "A table used for work-related tasks, often equipped with drawers and space for a computer." },
    { label: "End Table", value: "end_table", description: "A small table placed at the end of a sofa or beside a chair, used for lamps and decorative items." },
    { label: "Ficus Tree", value: "ficus_tree", description: "A popular indoor plant known for its glossy leaves and tree-like appearance." },
    { label: "Fern", value: "fern", description: "A plant with delicate, feathery fronds, often used to add greenery indoors." },
    { label: "Succulent", value: "succulent", description: "A small, low-maintenance plant known for its thick, water-storing leaves." },
    { label: "Orchid", value: "orchid", description: "A flowering plant known for its beautiful and exotic blooms." },
    { label: "Shower", value: "shower", description: "A bathroom element used for bathing, typically consisting of a showerhead and enclosure." },
    { label: "Bathtub", value: "bathtub", description: "A large container for holding water in which a person may bathe." },
    { label: "Toilet", value: "toilet", description: "A bathroom fixture used for the disposal of human waste." },
    { label: "Sink", value: "sink", description: "A basin used for washing hands, dishes, and other tasks, commonly found in bathrooms and kitchens." },
    { label: "Mirror", value: "mirror", description: "A reflective surface, often placed above a sink, used for grooming and decoration." },
    { label: "Refrigerator", value: "refrigerator", description: "A kitchen appliance used to keep food and beverages cold." },
    { label: "Oven", value: "oven", description: "A kitchen appliance used for baking, roasting, and heating food." },
    { label: "Stove", value: "stove", description: "A kitchen appliance with burners or a cooktop used for cooking food." },
    { label: "Microwave", value: "microwave", description: "A kitchen appliance that uses microwave radiation to quickly heat food." },
    { label: "Dishwasher", value: "dishwasher", description: "A kitchen appliance used to automatically wash and dry dishes." }
];
