export const doorTypes = [
    { label: "Hinged Door", value: "hinged", description: "A door mounted on hinges along one side allowing it to open and close." },
    { label: "Single Hinged Door", value: "single_hinged", description: "A door with a single leaf mounted on hinges." },
    { label: "Double Hinged Door", value: "double_hinged", description: "A pair of doors mounted on hinges, opening from the center." },
    { label: "Dutch Door", value: "dutch", description: "A door divided horizontally so that the top and bottom halves can be opened independently." },
    { label: "Sliding Door", value: "sliding", description: "A door that opens horizontally by sliding along a track." },
    { label: "Single Sliding Door", value: "single_sliding", description: "A single door panel that slides open along a track." },
    { label: "Double Sliding Door", value: "double_sliding", description: "Two door panels that slide open along parallel tracks." },
    { label: "Pocket Door", value: "pocket", description: "A door that slides into a compartment in the adjacent wall when opened." },
    { label: "Barn Door", value: "barn", description: "A sliding door mounted on a track above the doorway, often used for rustic or industrial aesthetics." },
    { label: "Folding Door", value: "folding", description: "A door made up of multiple panels that fold back against one another." },
    { label: "Bi-Fold Door", value: "bi_fold", description: "A door with two panels that fold back to one side." },
    { label: "Multi-Fold Door", value: "multi_fold", description: "A door with several panels that fold back in a concertina style." },
    { label: "Revolving Door", value: "revolving", description: "A door with multiple wings that rotate around a central axis, allowing multiple people to pass through simultaneously." },
    { label: "Pivot Door", value: "pivot", description: "A door that rotates on a pivot point rather than hinges, allowing for unique opening mechanisms." },
    { label: "Flush Door", value: "flush", description: "A flat, smooth door with a plain surface, typically used for interior doors." },
    { label: "Panel Door", value: "panel", description: "A door consisting of stiles and rails with panels in between." },
    { label: "Raised Panel Door", value: "raised_panel", description: "A panel door with raised central panels, adding depth and texture." },
    { label: "Flat Panel Door", value: "flat_panel", description: "A panel door with flat central panels, providing a simpler look." },
    { label: "Louvered Door", value: "louvered", description: "A door with horizontal slats to allow for ventilation while maintaining privacy." },
    { label: "Glazed Door", value: "glazed", description: "A door with glass panels, allowing light to pass through." },
    { label: "Full-Glass Door", value: "full_glass", description: "A door with a full glass panel, often used for exterior applications." },
    { label: "Half-Glass Door", value: "half_glass", description: "A door with a glass panel covering the upper half of the door." },
    { label: "Frosted Glass Door", value: "frosted_glass", description: "A door with frosted glass for privacy while still allowing light to pass through." },
    { label: "Stained Glass Door", value: "stained_glass", description: "A door with decorative stained glass panels, often used for aesthetic purposes." },
    { label: "Screen Door", value: "screen", description: "A door with a mesh screen to allow ventilation while keeping insects out." },
    { label: "Storm Door", value: "storm", description: "An additional outer door to protect against bad weather." },
    { label: "Fire-Rated Door", value: "fire_rated", description: "A door designed to resist the spread of fire for a specified period." },
    { label: "Security Door", value: "security", description: "A reinforced door designed to provide enhanced security against break-ins." },
    { label: "Pocket Door", value: "pocket", description: "A sliding door that disappears into a compartment in the adjacent wall." },
    { label: "Accordion Door", value: "accordion", description: "A door that folds in a manner similar to an accordion, often used for space-saving purposes." },
    { label: "Automatic Door", value: "automatic", description: "A door that opens and closes automatically, usually operated by sensors." },
    { label: "Double Leaf Door", value: "double_leaf", description: "A set of two doors that open from the center, each door being a single leaf." },
    { label: "Stable Door", value: "stable", description: "A door divided horizontally, allowing the top half to open independently of the bottom half." },
    { label: "French Door", value: "french", description: "Double doors with glass panes extending for most of their length, typically opening outwards." },
    { label: "Patio Door", value: "patio", description: "A door leading to a patio, typically large and often made of glass." },
    { label: "Sliding Patio Door", value: "sliding_patio", description: "A large glass door that slides open to provide access to a patio." },
    { label: "Hinged Patio Door", value: "hinged_patio", description: "A door with glass panels that swings open to provide access to a patio." },
    { label: "Garage Door", value: "garage", description: "A large door on a garage that can be opened to allow vehicles to enter and exit." },
    { label: "Sectional Garage Door", value: "sectional_garage", description: "A garage door made of several horizontal sections that lift up and fold overhead." },
    { label: "Roll-Up Garage Door", value: "roll_up_garage", description: "A garage door that rolls up into a coil above the opening." },
    { label: "Tilt-Up Garage Door", value: "tilt_up_garage", description: "A single panel garage door that tilts up and swings out when opened." }
];
