export const planTypes = [
    { label: "Flat Interior", value: "flat_interior", description: "Blueprints and plans for the interior layout and design of a flat or apartment." },
    { label: "House Interior", value: "house_interior", description: "Blueprints and plans for the interior layout and design of a house." },
    { label: "House Exterior", value: "house_exterior", description: "Blueprints and plans for the exterior design and structure of a house." },
    { label: "Camper Van", value: "camper_van", description: "Blueprints and plans for the interior layout and customization of a camper van." },
    { label: "Commercial Interior", value: "commercial_interior", description: "Blueprints and plans for the interior layout and design of commercial spaces like offices, shops, or restaurants." },
    { label: "Landscape", value: "landscape", description: "Blueprints and plans for the design and layout of outdoor spaces, including gardens and parks." },
    { label: "Industrial Interior", value: "industrial_interior", description: "Blueprints and plans for the interior layout and design of industrial buildings like factories and warehouses." },
    { label: "Warehouse Interior", value: "warehouse_interior", description: "Blueprints and plans for the interior layout and storage solutions of a warehouse." },
    { label: "Retail Store", value: "retail_store", description: "Blueprints and plans for the interior layout and design of retail stores and shopping centers." },
    { label: "Hotel Interior", value: "hotel_interior", description: "Blueprints and plans for the interior layout and design of hotels." },
    { label: "Public Building Interior", value: "public_building_interior", description: "Blueprints and plans for the interior layout and design of public buildings like libraries and community centers." },
    { label: "School Interior", value: "school_interior", description: "Blueprints and plans for the interior layout and design of educational institutions like schools and universities." },
    { label: "Hospital Interior", value: "hospital_interior", description: "Blueprints and plans for the interior layout and design of healthcare facilities like hospitals and clinics." },
    { label: "Restaurant Interior", value: "restaurant_interior", description: "Blueprints and plans for the interior layout and design of restaurants and cafes." },
    { label: "Sports Facility Interior", value: "sports_facility_interior", description: "Blueprints and plans for the interior layout and design of sports facilities like gyms and stadiums." },
    { label: "Residential Complex Interior", value: "residential_complex_interior", description: "Blueprints and plans for the interior layout and design of residential complexes." },
    { label: "Garage Interior", value: "garage_interior", description: "Blueprints and plans for the interior layout and design of garages." },
    { label: "Museum Interior", value: "museum_interior", description: "Blueprints and plans for the interior layout and design of museums." },
    { label: "Church Interior", value: "church_interior", description: "Blueprints and plans for the interior layout and design of churches and other religious buildings." },
    { label: "Airport Interior", value: "airport_interior", description: "Blueprints and plans for the interior layout and design of airport terminals and facilities." }
];
