export const windowTypes = [
    { label: "Single-Hung Window", value: "single_hung", description: "A window with two sashes, where only the bottom sash moves up and down." },
    { label: "Double-Hung Window", value: "double_hung", description: "A window with two sashes that can move up and down independently." },
    { label: "Sliding Window", value: "sliding", description: "A window with one or more sashes that slide horizontally." },
    { label: "Casement Window", value: "casement", description: "A window attached to its frame by one or more hinges, opening outward like a door." },
    { label: "Awning Window", value: "awning", description: "A window hinged at the top, opening outward from the bottom." },
    { label: "Hopper Window", value: "hopper", description: "A window hinged at the bottom, opening inward from the top." },
    { label: "Bay Window", value: "bay", description: "A window that protrudes outward from an exterior wall, creating a small shelf." },
    { label: "Bow Window", value: "bow", description: "A curved window that protrudes outward from an exterior wall, creating a rounded appearance." },
    { label: "Picture Window", value: "picture", description: "A large, fixed window designed to provide an unobstructed view." },
    { label: "Transom Window", value: "transom", description: "A window above a door or another window, often used for additional light." },
    { label: "Skylight", value: "skylight", description: "A window installed in a roof or ceiling to allow natural light to enter." },
    { label: "Garden Window", value: "garden", description: "A three-dimensional window that extends outward, providing space for plants." },
    { label: "Jalousie Window", value: "jalousie", description: "A window consisting of parallel glass, acrylic, or wooden louvers that open and close simultaneously." },
    { label: "Tilt and Turn Window", value: "tilt_and_turn", description: "A window that can tilt inward at the top or swing open inward like a door." },
    { label: "Fixed Window", value: "fixed", description: "A non-operable window designed to let in light and provide views." },
    { label: "Arched Window", value: "arched", description: "A window with a rounded or arched top." },
    { label: "Egress Window", value: "egress", description: "A window large enough and positioned for emergency escape or rescue." },
    { label: "Storm Window", value: "storm", description: "A second window installed outside or inside a primary window to protect against bad weather." },
    { label: "Glass Block Window", value: "glass_block", description: "A window made from glass blocks, providing privacy while allowing light to pass through." },
    { label: "Bay and Bow Window", value: "bay_bow", description: "A combination of bay and bow windows to create a large protruding window space." },
    { label: "Corner Window", value: "corner", description: "A window that wraps around the corner of a building, providing views from two different sides." },
    { label: "Round Window", value: "round", description: "A circular window, often used as a decorative element." },
    { label: "Oval Window", value: "oval", description: "An oval-shaped window, often used for decorative purposes." },
    { label: "Clerestory Window", value: "clerestory", description: "A high window in a wall that allows light to enter a room while maintaining privacy." }
];
